### ISSUE TITLE
The link to database doesnt work for me.

### ISSUE THREAD

**Issue by pkd2989** [zhenqifu/SIRQA#1]
Can you please check if the link to the dataset working?

**Comment by zhenqifu** [comment]
Hi, the link is OK. Please try again.

**Comment by pkd2989** [comment]
![image](https://user-images.githubusercontent.com/68956997/148933138-5a5ffe61-5569-4cbb-bab5-df3300ba86b0.png)

I am getting this error

**Comment by zhenqifu** [comment]
Please contact me via email. I can send it to you.

**Comment by pkd2989** [comment]
The links are inaccessible. According the error message while trying to create account, the Baidu server doesn't allowing to register and create account outside China. I suggest you to place a copy of dateset somewhere publicly accessible.

Regards

**Comment by zhenqifu** [comment]
I see. I will upload the dataset to Google Drive. Once the link is made, I will email you.&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhenqifu/SIRQA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 晚上9:39
***@***.***&gt;;
抄送:&nbsp;"Zhenqi ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhenqifu/SIRQA] The link to database doesnt work for me. (Issue #1)





 
The links are inaccessible. According the error message while trying to create account, the Baidu server doesn't allowing to register and create account outside China. I suggest you to place a copy of dateset somewhere publicly accessible.
 
Regards
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
